export const supabaseUrl = 'https://telwykbrnnqqsbbhmbum.supabase.co'
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbHd5a2Jybm5xcXNiYmhtYnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY2MjY0MjQsImV4cCI6MjEwMjIwMjQyNH0._fEIbHzyHtIGboT0Q6zAL2vMGXquQWj9I92yfmymF6Y'
